NucleciAcid ::= Dna | Rna;
Dna ::= { DnaCode };
Rna ::= { RnaCode };
DnaCode ::= DnaBase DnaBase DnaBase;
DnaBase ::= Adenine | Cytosine | Guanine | Thymine | Delete;
RnaCode ::= RnaBase RnaBase RnaBase;
RnaBase ::= Adenine | Cytosine | Guanine | Uracil | Delete;
Adenine ::= 'A';
Cytosine ::= 'C';
Guanine ::= 'G';
Thymine ::= 'T';
Uracil ::= 'U';
Delete ::= '-';